name: Docker Compose 镜像安全扫描
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 构建镜像
        run: docker-compose build

      # 扫描第一个镜像
      - name: 扫描 docker-compose-web
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --network=host \
            sas-image-scanner-registry.cn-hangzhou.cr.aliyuncs.com/sas_public/sas-image-scanner:latest \
            --accessKeyId=${{ secrets.ACCESSKEYID }} \
            --accessKeySecret=${{ secrets.ACCESSKEYSECRET }} \
            --token=${{ secrets.SAS_TOKEN }} \
            --imageId=docker-compose-web:latest

      # 扫描第二个镜像
      - name: 扫描 docker-compose-server
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --network=host \
            sas-image-scanner-registry.cn-hangzhou.cr.aliyuncs.com/sas_public/sas-image-scanner:latest \
            --accessKeyId=${{ secrets.ACCESSKEYID }} \
            --accessKeySecret=${{ secrets.ACCESSKEYSECRET }} \
            --token=${{ secrets.SAS_TOKEN }} \
            --imageId=docker-compose-server:latest
